complete task
mate-academy/js_task_generate_table_DOM pull request #1202
Opened 2024-09-12 20:18 UTC by RomanMartseniuk

- [DEMO LINK](https://RomanMartseniuk.github.io/js_task_generate_table_DOM/)

2024-09-13 05:49 UTC, lerastarynets requested changes
Pls try to pass all tests, if your tests pass locally, but you encounter a problem in server tests, pls attach a screen of all local tests passing

2024-09-16 19:26 UTC, RomanMartseniuk commented
![image](https://github.com/user-attachments/assets/599e0176-5cb0-43f6-b037-63b7033defe0)

2024-09-16 19:31 UTC, etojeDenys approved these changes

2024-09-16 19:31 UTC, etojeDenys commented on src/scripts/main.js
> +const TABLE = document.querySelector('.dashboard');
```suggestion
const table = document.querySelector('.dashboard');
```

2025-12-26 20:57 UTC, closed without merging