js_task_generate_table_DOM
mate-academy/js_task_generate_table_DOM pull request #189
Opened 2021-03-04 14:28 UTC by SofiiaAsieieva

[DEMO LINK](https://SofiiaAsieieva.github.io/js_task_generate_table_DOM/)

2021-03-04 15:47 UTC, misha-lysak approved these changes
![image](https://user-images.githubusercontent.com/63812444/109990001-ae78cb00-7d11-11eb-977a-bdf1b4f6288a.png)

2021-03-05 08:39 UTC, Vladimir-Beliy requested changes

2021-03-05 08:39 UTC, Vladimir-Beliy commented on src/scripts/main.js
> +function convertingAPeopleObjectToATable(men) {
```suggestion
function createTableWithPeople(men) {
```

2021-03-05 09:03 UTC, Vladimir-Beliy approved these changes

2026-02-02 19:57 UTC, closed without merging