Table of people
mate-academy/js_task_generate_table_DOM pull request #236
Opened 2021-04-26 14:28 UTC by ivan-major

2021-04-27 11:53 UTC, vpolets requested changes
![image](https://user-images.githubusercontent.com/46418908/116236841-34d8e880-a768-11eb-8a1f-e9327b261315.png)
немає gh-pages

2021-04-27 11:53 UTC, vpolets commented on src/scripts/main.js
> +for (let x = 0; x < people.length; x++) {
`i` прийнято в циклі використовувати

2021-04-27 11:53 UTC, vpolets commented on src/scripts/main.js
> +};
`i`

2021-04-27 11:53 UTC, vpolets commented on src/scripts/main.js
> +  };
спрости до тринарника

2021-04-27 19:09 UTC, ivan-major commented
Не можу зрозуміти, чому не підтягується сторінка із змінами. Все роблю по інструкції. При запуску старт із VSC сторінка запускається. Але все одно помилка 404. Чи можливо по новому загрузити та зробити завдання? Спробува, але мені не дало знову загрузити файли.

2021-04-28 08:32 UTC, vpolets requested changes
Якщо тести не проходять то завдання не зальється на gh-pages)

2021-04-30 16:27 UTC, vpolets approved these changes

2025-01-26 13:12 UTC, closed without merging